language: node_js
node_js:
  - "node" # Latest stable

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master

branches:
  only:
    master

script:
  - npm run lint
  - npm run build
